### PR TITLE
rails 5 support

### PR DESCRIPTION
**Pull request by googya**
it does not work in rails 5, adding 5 support

### CODE REVIEW

**Comment by ifool** [comment]
How about change
```ruby
if Rails.version =~ /^[345]/
```
to
```ruby
if Rails.version.to_i > 2
```
?

**Comment by liangwenke** [comment]
牛逼啊

**Comment by liangwenke** [comment]
@ifool 牛逼啊，已经合并了。

**Comment by liangwenke** [comment]
@googya 感谢你的贡献！

**Pull request merged**
